---
driver:
  synced_folders: [["/vagrant/binaries", "/vagrant/binaries"]]
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4
  - name: ubuntu-12.04
suites:
  - name: default
    run_list:
      - recipe[df_ruby::default]
    attributes:
